=== Maserati-666/HTML_and_XML/XML/Task3/lessons_XML.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="lessons">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="discipline" type="disciplineinfo"/>
        <xs:element name="discipline" type="disciplineinfo"/>
        <xs:element name="discipline" type="disciplineinfo"/>
        <xs:element name="discipline" type="disciplineinfo"/>
        <xs:element name="discipline" type="disciplineinfo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="disciplineinfo">
    <xs:sequence>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="Teacher" type="xs:string"/>
      <xs:element name="StartDate" type="xs:string"/>
      <xs:element name="EndDate" type="xs:string"/>
      <xs:element name="NumberOfHours" type="xs:unsignedByte"/>
      <xs:element name="FinalGrade" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string"/>
  </xs:complexType>
</xs:schema>

=== Maserati-666/HTML_and_XML/XML/Task3/lessons.xml
<?xml version="1.0" encoding="UTF-8"?>
<lessons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/A_SER/Repositories/ITMO/HTML_and_XML/XML/Task3/lessons_XML.xsd">
  <discipline id = "d1">
    <Name>Технологии программирования</Name>
    <Teacher>Ямщиков Д.В.</Teacher>
    <StartDate>27.03.2023</StartDate>
    <EndDate>11.04.2023</EndDate>
    <NumberOfHours>45</NumberOfHours>
    <FinalGrade>Зачет</FinalGrade>
  </discipline>
  <discipline id = "d2">
    <Name>Программирование на C#</Name>
    <Teacher>Осипов Н.А.</Teacher>
    <StartDate>13.04.2023</StartDate>
    <EndDate>04.05.2023</EndDate>
    <NumberOfHours>50</NumberOfHours>
    <FinalGrade>Зачет</FinalGrade>
  </discipline>
  <discipline id = "d3">
    <Name>Разработка Windows-приложений на C#</Name>
    <Teacher>Смольянинов А.В.</Teacher>
    <StartDate>10.05.2023</StartDate>
    <EndDate>31.05.2023</EndDate>
    <NumberOfHours>50</NumberOfHours>
    <FinalGrade>Экзамен</FinalGrade>
  </discipline>
  <discipline id = "d4">
    <Name>Введение в базы данных</Name>
    <Teacher>Осетрова И.С.</Teacher>
    <StartDate>05.06.2023</StartDate>
    <EndDate>23.06.2023</EndDate>
    <NumberOfHours>35</NumberOfHours>
    <FinalGrade>Зачет</FinalGrade>
  </discipline>
  <discipline id = "d5">
    <Name>Основы технологий разметки (HTML, XML)</Name>
    <Teacher>Кузьмин К.М.</Teacher>
    <StartDate>26.06.2023</StartDate>
    <EndDate>04.07.2023</EndDate>
    <NumberOfHours>25</NumberOfHours>
    <FinalGrade>Зачет</FinalGrade>
  </discipline>
</lessons>
